title: NullDoot2k
subtitle: A OniOps From Internet
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  - text: Video
    url: /video
  - text: Contact
    url: /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: me.jpg
author: NullDoot2k
author_bio: Hi, my name is NullDoot(DATV), Student at University of Transport Technology, University student with 2 years of development experience in Dev, Sec and Net, freelance with experience and high knowledge of design management implementation and develop web applications, creating quality products for users.
author_info: I ran into an obstacle in my life but I collected a bonus, the bonus it's the skills "IT". You have to think about all the things you have, you know that in many countries no one can afford to study on a computer, consider yourself lucky in fate.
author_email: "nulldoot2k@proton.me"
author_location: VietNam
author_website_url: "https://datv.nulldoot2k.xyz"
typewrite-text: The fastest way is to connect to the IRC on webchat and join nulldoot with us right now. For general questions about using IRC, click HERE.
hero_cover_img: itaboutme.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Future
author_future:
  - skill_future1: Ui/Ux Designer
    in_skill_design: Interface development
    in_skill_design1: Website development
    in_skill_design2: Creating UI-UX element interactions
    in_skill_design3: Always come up with new ideas
    in_skill_design4: Improved good looking interface
    visibility: true
  - skill_future2: Fullstack DevOps
    in_skill_devops: Lead the DevOps department, help the team to solve the problems
    in_skill_devops1: Application development web/app…
    in_skill_devops2: Optimize the system quickly
    in_skill_devops3: Improve security, risk, patch vulnerabilities
    in_skill_devops4: Improve user access speed
    visibility: true
  - skill_future3: Freelancer AnonOps
    in_skill_anonops: I’m working freelance in cyberspace
    in_skill_anonops1: Anonops - a world without rules
    in_skill_anonops2: I’m always there for you, if you need me
    in_skill_anonops3: Chat channel OniOps with joinus
    visibility: true

# Experiences
author_work_experiences:
  - company_name: AWS
    company_logo: aws.png
    company_url: https://aws.amazon.com
    designation: Software Engineer
    description: Worked on various AWS Cloud Products
    visibility: true
  - company_name: Elasa
    company_logo: elsaga.png
    company_url: https://elsaga.net
    designation: DevOps - SysAdmin
    description: Worked on various Cloud Products and Building System
    visibility: true

# Education
author_education_details:
  - college_logo: utt.png
    college_name: UTT
    college_url: https://utt.edu.vn
    college_degree: Studient
    description: University Technology of Transport
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: churongcon.png
    project_title: King DATV
    project_description: A Platform built for Blog Paper Website
    project_url: http://churongcondatv.42web.io
    visibility: true
  - project_thumbnail: hack4r.PNG
    project_title: Hack4r
    project_description: A Platform built for Hackers and Penetration Testers
    project_url: https://www.hack4r.com
    visibility: true

# social links
twitter_username: Null Doot
github_username: CompanyDATV
facebook_username: Vu Manh Dat
linkedin_username: DATV
instagram_username: kanz_vdat
telegram_username: nulldoot2k

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: nulldoot2k

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://us9.list-manage.com/contact-form?u=e9c73f31408d3aac28a36f444&form_id=8623aaef6f4cd95d5da93459a58038ca

# contact form - (choose formspress or getform)
getform_endpoint: 2a22edc3-eae1-4aec-99b5-1b4e8544cd72
formspree_email: nulldoot2k@proton.me

# releases - widget can be (sidebar, modal or embed)
olvy_organization: OniOps
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true
show_author_future: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: "/category/:name/"

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
